### ISSUE TITLE
get makefile to respect dependencies

### ISSUE THREAD

**Issue by mk270** [mk270/whitakers-words#24]

**Comment by Fuco1** [comment]
Do we even need a Makefile if the build is done with `gprbuild`? Or is it only going to be used to build the datafiles?  That could probably be included somehow.

Yesterday someone from the `#latin` IRC tried to build this project and could't because the `gprbuild` package isn't available in all debian repos (on top of that he runs arm architecture).  It's a pretty nasty dependency imo.

A pure makefile & gnat/gcc solution would be preferable for me, but it's much more work maintaining (as I understand the gpr system does a lot of package logic automatically).

**Comment by mk270** [comment]
I have come round to the pure Makefile solution too.

gprbuild effectively imports GNAT GPL, which can't be used to distribute binaries of WORDS (see discussion at #2)

I'm sorry for breaking your earlier work on the Makefile - but the split directories thing was important too.

**Comment by darkestkhan** [comment]
gprbuild doesn't import GNAT GPL. I have gprbuild on Debian and no gnat gpl - only gnat fsf.
The problem with gnatmake is that it is losing some capabilities in newest gnat versions. In particular ability to build libraries.

Beside from what I saw (just checked) it is accessible on all architectures (definitely on all arm ports of Debian post squeeze)

**Comment by mk270** [comment]
The issue is on Windows, not on Debian - have you got gprbuild working there too with GNAT FSF?

**Comment by darkestkhan** [comment]
There is tdm-gcc [fsf gcc tree build natively for windows] which provides gcc, g++ AND gnat (among others). IIRC it also provides gprbuild. If not, I can provide one myself.

**Comment by mk270** [comment]
ok - I'll look into tdm-gcc ; this may mean we can keep gprbuild; thanks again for the info!

**Comment by mk270** [comment]
I've looked into tdm-gcc - can't find gprbuild; what are our options?

**Comment by darkestkhan** [comment]
building it ourselves and/or providing configuration for one from gnat gpl. I will ask on #ada cause I know that there are some people who do have working windows version of gprbuild with configurations for gnat fsf.
