### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by aethralis** [mk270/whitakers-words#84]
I downloaded the files and followed make instructions and get the following error:

```
raised SYSTEM.ASSERTIONS.ASSERT_FAILURE : binde.adb:1005
gprlib: invocation of /usr/bin/gnatbind failed
gprbuild: could not build library for project words_engine
Makefile:6: recipe for target 'bin/words' failed
make: *** [bin/words] Error 4
```

This is on Ubuntu 17.10 (beta), on the previous version of Ubuntu the process was successful.

**Comment by mk270** [comment]
For the time being, let's document in the README that building it on Ubuntu 17.10 beta isn't currently supported, and work out what to do about it.

I suspect that the error is because our build procedures are taking liberties and newer versions of the Ada toolchain are too strict, thus we may in due course need to adapt our build procedures.

**Comment by mk270** [comment]
It fails with gnat-7 in general

**Comment by aethralis** [comment]
I tried to work around this and create a snap package using the older version of gnat, but that also was unsuccessful. Perhaps this has to do with my very limited understanding of creating such packages.

**Comment by Jbithell** [comment]
Getting same error on `Ubuntu 18.04.1 x64`

```
raised SYSTEM.ASSERTIONS.ASSERT_FAILURE : binde.adb:1005
gprlib: invocation of /usr/bin/gnatbind failed
gprbuild: could not build library for project words_engine
Makefile:6: recipe for target 'bin/words' failed
make: *** [bin/words] Error 4
```

**Comment by mk270** [comment]
I have found that this problem occurs with gnat-8 as well as gnat-7, but not with gnat-6; this implies that it is an ongoing compiler feature, rather than a problem limited to gnat-7. If true, then we'll have to deal with it, rather than just say "don't use gnat-7".

I suspect that something about how we're building WORDS is against the rules or best practice, and needs to be fixed, and that we might be able to isolate it with git bisect (and that it'll be to do with shared vs dynamic libraries)

**Comment by mk270** [comment]
sure enough, commit 2ff0fa3838ceccffac44b0a9a6c92e7bc8bdcb80 seems to be the problem, according to ```git bisect```

**Comment by mk270** [comment]
Looks like there may be a bug in the toolchain; I have switched to using static libraries.
